jobs:
  terraform:
    env:
      AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
      AWS_DEFAULT_REGION: ap-southeast-2
      AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      AWS_LOAD_CONFIG: 1
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.25
          cli_config_credentials_hostname: 'dev.github.uts.edu.au'
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: pwd
        run: pwd
      - name: ls
        run: ls
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -diff
        continue-on-error: true

      - name: terraform init
        id: init
        run: terraform init
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
name: Format and validate and plan
"on":
  push:
    branches:
      - CZ-1013
  pull_request: